# Generated by Django 5.0.4 on 2024-04-13 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
