# Generated by Django 5.0.4 on 2024-04-13 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_user_id_alter_user_temp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
