# Generated by Django 5.0.4 on 2024-04-13 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="temp_id",
            new_name="id",
        ),
    ]
