# Generated by Django 5.0.4 on 2024-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="reset",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
